version: '3.3'
services:
  web:
    image: herlesinc/odoo14ce:1.0
    container_name: odooprod14
    domainname: odooprod14.local
    hostname: odooprod14
    networks:
      net:
        ipv4_address: 10.10.1.100
    volumes:
      - ./addons:/mnt/extra-addons/
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./autostart.sh:/mnt/extra-addons/autostart.sh
      - odoo-web-data:/var/lib/odoo/odooprod
    restart: always
    stdin_open: true
    tty: true
    command: "/mnt/extra-addons/autostart.sh"
volumes:
  odoo-web-data:
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
